### ISSUE TITLE
Generación del modelo de datos para Ingresos

### ISSUE THREAD

**Issue by mcguegi** [udistrital/financiera_mongo_crud#11]
Generar el modelo de datos para el nuevo microservicio de ingresos, lo cual comprende las siguientes subtareas:

 
- [ ] Creación del modelo en pgmodeler de acuerdo a los lineamientos
- [ ] Documentación de los objetos y campos de acuerdo al documento de análisis
- [ ] Generación del script para creación de la base de datos

**Comment by juancsr** [comment]
¿Esta tarea todavía se está realizando?

**Comment by mcguegi** [comment]
No se está realizando esta tarea dado que esta tarea no corresponde al sprint actual ni al de la otra semana.

**Comment by Soulfilip-UD** [comment]
La tarea se suspende el Issue se cierra
