### ISSUE TITLE
Correccion de libreria mgo y beego.Error

### ISSUE THREAD

**Issue by davidmm07** [udistrital/financiera_mongo_crud#9]
corregir error en las peticiones de arboles de rubros

**Comment by davidmm07** [comment]
debido a que el despliegue del api de mongo esta basado en contenedor, la versión de beego se actualiza, por eso se tuvieron que hacer los respectivos cambios para levantar el servicio, tarea realizada a finales de Abril , los commits correspondientes son:
https://github.com/udistrital/financiera_mongo_crud/commit/20d3a1f7b3ae5598bdda3f7a0ea4d5fa0686f521
https://github.com/udistrital/financiera_mongo_crud/commit/8e11a53388c312fdd0718c4b1e967ac76d374129
https://github.com/udistrital/financiera_mongo_crud/commit/ee193e8d19fc44394c70d96465d2e0a321e4d032

https://github.com/udistrital/financiera_mongo_crud/commit/3eb0c412364a0ae3bdfe3944ecb47d4eab5a3c43

**Comment by miguelramirez93** [comment]
Se revisa la actualización de la configuración y funciona correctamente.
